# name: quiz_app
# description: "A new Flutter project."

# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: ^3.6.0

# dependencies:
#   flutter:
#     sdk: flutter
#   cupertino_icons: ^1.0.8
#   provider: ^6.0.0
#   firebase_core: ^3.10.0 # Update to the required version
#   firebase_auth: ^5.4.0
#   cloud_firestore: ^5.4.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^5.0.0

# flutter:
#   uses-material-design: true

#   assets:
#     - assets/images/quiz-logo.png

name: quiz_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  firebase_storage: ^12.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/quiz-logo.png